version: '3.8'

services:
    api:
        build:
            context: server/
            dockerfile: Dockerfile
        entrypoint: ['/usr/src/app/entrypoint.sh']
        ports:
            - 5004:5000
        volumes: 
            - './server:/usr/src/app'
        environment: 
            - FLASK_DEBUG=1
            - APP_SETTINGS=src.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
        depends_on: 
            - api-db
    
    api-db:
        build:
            context: server/src/db
            dockerfile: Dockerfile
        expose: 
            - 5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

